### PR TITLE
Logging Issues Hopefully Resolved

### PR DESCRIPTION
**Pull request by AdityaSoni19031997**

### CODE REVIEW

**Comment by shaz13** [comment]
Same error @AdityaSoni19031997. 

> When run bash scripts/start.sh

Screenshot 2020-04-02 at 9 34 23 PM

> If run python main.py

Now, no logs are generated at all

**Review by shaz13-socgen — CHANGES_REQUESTED** [review]
Can we make it more general and move out of gunicorn. So its platform independent

**Comment by AdityaSoni19031997** [comment]
Is it that there's nothing written to that file even after hitting localhost:8000?
>If run python main.py, Now, no logs are generated at all

Then logs should go to "werkzeug.log"

**Comment by AdityaSoni19031997** [comment]
>Can we make it more general and move out of gunicorn. So its platform independent.

I think, i will club them into a single log file? If that's sound okay, let me know.

**Comment by shaz13-socgen** [comment]
Yes that's ok to have one log file @AdityaSoni19031997

**Comment by shaz13-socgen** [comment]
Any progress ?

**Comment by AdityaSoni19031997** [comment]
Sorry i didn't push it back; Let me know if it runs for you now;

**Review by AdityaSoni19031997 — COMMENTED** [review]
I hope it work's now

**Comment by shaz13** [comment]
Working fine on Linux  + Docker

**Comment by AdityaSoni19031997** [comment]
Great :)

**Pull request closed without merging**
