### PR TITLE
Added Miminal DL (MNIST) Example

### PR DESCRIPTION
**Pull request by AdityaSoni19031997**
Added Miminal DL (MNIST) Example

### CODE REVIEW

**Comment by AdityaSoni19031997** [comment]
Can we have pip's version as "20.0.2"?

>ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from -r requirements.txt (line 35)) (from versions: 2.2.0rc1)
ERROR: No matching distribution found for tensorflow==1.15.0 (from -r requirements.txt (line 35))

**Comment by shaz13-socgen** [comment]
Sure you can try editing the build config in `.github` folder. Also, I think its good to research on most used pip versions (especially that comes with Python 3.6)

**Comment by shaz13-socgen** [comment]
Also + your commits are coming again from previous merge. So, this PR is again with bad history. Please make a new branch and then push another PR (after pulling from current master from @shaz13) and close this one :) 

This account will be a solely review account for the repo

**Review by shaz13-socgen — COMMENTED** [review]
Done

**Comment by AdityaSoni19031997** [comment]
The latest pip version is 20.0.2 (2020-01-24)

**Pull request closed without merging**
